### ISSUE TITLE
Different android ID

### ISSUE THREAD

**Issue by RasulM97** [fluttercommunity/android_id#13]
Outputting by different devices will generate different Android ID in same android device.
I released a sample apk with 2 computers and the result as you see is completely different.
![Screenshot_20221106-092637](https://user-images.githubusercontent.com/85100446/200156605-e3666716-22bd-460f-835f-64bd6ecc2289.png)

**Comment by nohli** [comment]
Hi @RasulM97 please help me to better understand the description.

Are the screenshots from different devices? From emulators?

**Comment by RasulM97** [comment]
> Hi @RasulM97 please help me to better understand the description.
> 
> Are the screenshots from different devices? From emulators?

Hello dear @nohli 
these apps are running on my phone, and the screenshot is in one screen.
My friend and I are working on a project, when one of us published a release APK with ourselves computers, the android ID generated different.
Top picture is my release by my computer, bottom picture is my friend's release by his computer.

**Comment by nohli** [comment]
@RasulM97 thanks a lot for the great clarification! ☺️

Apparently, this is expected behavior:
https://stackoverflow.com/a/43393373

If you use the same signing keys for both builds, the id should be the same:
`The ANDROID_ID value won't change on package uninstall/reinstall, as long as the package name and signing key are the same. Apps can rely on this value to maintain state across reinstalls.`

This should be made more clear in the docs of this package though. Would you be interested in adding it to the README/docs?
(I'm thinking about the column about Android ID from [here](https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html?m=1))

**Comment by nohli** [comment]
I've updated the README with some explanations and links.

The issue you're describing is expected behavior when retrieving `Settings.Secure.ANDROID_ID`, like with the help of this plugin.

**Comment by RasulM97** [comment]
@nohli 
Thanks for your responding.👍
Woman, life, freedom

**Comment by nohli** [comment]
> @nohli 
> 
> Thanks for your responding.👍
> 
> Woman, life, freedom

Khahesh mikonam 😊🤝🏾
